# Generated by Django 5.2.17 on 2026-09-30 13:03

import django.db.models.deletion
import drf_totp.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_totp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="totpauth",
            name="otp_auth_url",
        ),
        migrations.AddField(
            model_name="totpauth",
            name="failed_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totpauth",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="totpauth",
            name="last_used_step",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="totpauth",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="totpauth",
            name="otp_base32",
            field=drf_totp.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.CreateModel(
            name="TOTPBackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_codes",
                        to="drf_totp.totpauth",
                    ),
                ),
            ],
            options={
                "verbose_name": "TOTP Backup Code",
                "verbose_name_plural": "TOTP Backup Codes",
            },
        ),
    ]
