name: Debug Release Creation

on:
  push:
    branches: 
      - main

jobs:
  debug-version-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install toml requests

    - name: Debug Version and Release Process
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Detailed debugging script
        echo "=== Repository Information ==="
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "Commit SHA: ${{ github.sha }}"
        
        echo -e "\n=== Python Version Check ==="
        python --version
        
        echo -e "\n=== pyproject.toml Contents ==="
        cat pyproject.toml
        
        echo -e "\n=== Extract Version from pyproject.toml ==="
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        echo "Extracted Version: $VERSION"
        
        echo -e "\n=== Existing GitHub Releases ==="
        gh release list --repo "${{ github.repository }}"
        
        echo -e "\n=== Attempting to Create Release ==="
        # Attempt to create release with verbose logging
        gh release create "v$VERSION" \
          --repo "${{ github.repository }}" \
          --title "Release $VERSION" \
          --notes "Automated release for version $VERSION" \
          --verbose || echo "Release creation failed"